# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 4 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: dbyll
google_analytics: dbyll
title: Ferhat AKBULUT

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Ferhat AKBULUT

description: ferhatakbulut, ferhat akbulut, ferhatakblt, ferhat, akbulut
author:
  name: ferhatakbulut
  email: ferhatakblt@gmail.com
  github: ferhatakbulut
  twitter: feratakblt
  pinterest: ferhatakblt_
  linkedin: ferhatakbulut
  bio: 12 Dev Adam 
  email_md5: c82e145928582f595aa3aa

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html
about_path: about.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

plugins:
  - jekyll-paginate
